<?php
function get_help_authorized_user_content(){
	$content = '<p class="rtejustify"><strong>1.How to upload old or manual principal employer registration data using excel file?</p></strong>';
	$content .= '<p class="rtejustify"><strong>Ans.</strong>The steps should be followed to upload Principal employer registration data using Excel file are:- 
										</br> <strong>Step 1:</strong> Click on <strong>"Add new P.E."</strong> under  menu <strong>"OLD/OFFLINE DATA"</strong>. 
										</br> <strong>Step 2:</strong> Click the hyperlink <strong>"here"</strong> to download the Excel format.
										</br> <strong>Step 3:</strong> After filling the Principal Employer registration data in the downloaded Excel Sheet in the specified format, upload the Excel sheet containing the Principal Employer details in the upload Section.
										</br> <strong>Step 4:</strong> After successful upload of the Excel sheet, you can see the Principal Employer Lists in the <strong>"P.E. list"</strong> under <strong>"OLD/OFFLINE DATA"</strong> menu.<br>
										 <iframe width="560" height="315" src="https://www.youtube.com/embed/vowgqImCleI" frameborder="0" allowfullscreen></iframe>  
										</p>';
	
	$content .= '<p class="rtejustify"><strong>2.Why will you upload Principal Employer details? </p></strong>';
	$content .= '<p class="rtejustify"><strong>Ans.</strong> Principal Employers details has to be upload so that old/manual regsitration number holders can apply for amendment by taking the reference number from the list uploaded by the Officials.	</p>';
	return $content;
}
?>